name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do frontend
        working-directory: client
        run: npm install

      - name: Rodar testes do frontend
        working-directory: client
        run: npm test -- --watchAll=false

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Rodar testes do backend
        working-directory: api
        run: ./mvnw test
